(()=>{"use strict";
const KEY="tripspend.v1";
const CURS=["OMR","AED","SAR","QAR","KWD","BHD","USD","EUR","GBP","THB","IDR","JPY","MYR","SGD","INR","TRY","CHF","AUD","CAD","NZD","CNY","KRW","PHP","VND"];
const DESTS=["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Republic of the Congo", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe", "Multiple countries / Other"];
const CATS=[["Food","🍽️"],["Transport","🚕"],["Hotel","🏨"],["Shopping","🛍️"],["Activities","🎟️"],["Flights","✈️"],["Coffee","☕"],["Groceries","🛒"],["Other","🧾"]];
const PAYS=["Cash","Credit Card","Debit Card","Apple Pay","Other"];
const KEYWORDS={Coffee:["coffee","cafe","café","latte","espresso","starbucks"],Food:["dinner","lunch","breakfast","restaurant","meal","burger","pizza","sushi","food","brunch"],Transport:["taxi","uber","grab","careem","metro","bus","train","fuel","gas","parking","toll"],Hotel:["hotel","resort","room","booking","airbnb","hostel"],Shopping:["shopping","mall","clothes","shirt","shoes","souvenir","gift"],Activities:["ticket","tour","museum","spa","massage","activity","excursion","park"],Flights:["flight","airline","airport","baggage","luggage"],Groceries:["grocery","groceries","supermarket","market","water","snacks"]};
const $=id=>document.getElementById(id);
let state=load();let installPrompt=null;let suggestedCategory="";
function blank(){return{trip:null,expenses:[],rates:{}}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==="object"?{trip:x.trip||null,expenses:Array.isArray(x.expenses)?x.expenses:[],rates:x.rates&&typeof x.rates==="object"?x.rates:{}}:blank()}catch{return blank()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function today(){const d=new Date;return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function dlocal(s){if(!s)return null;const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function days(a,b){const x=dlocal(a),y=dlocal(b);return x&&y?Math.max(0,Math.floor((y-x)/86400000)+1):0}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function money(v,c){const n=num(v),dec=["OMR","KWD","BHD"].includes(c)?3:2;return new Intl.NumberFormat(undefined,{minimumFractionDigits:dec,maximumFractionDigits:dec}).format(n)+" "+c}
function fmtDate(s){const d=dlocal(s);return d?new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short"}).format(d):""}
function fmtDateLong(s){const d=dlocal(s);return d?new Intl.DateTimeFormat(undefined,{weekday:"short",day:"numeric",month:"short"}).format(d):""}
function opts(el,arr,sel){el.replaceChildren();arr.forEach(x=>{const v=Array.isArray(x)?x[0]:x,t=Array.isArray(x)?`${x[1]} ${x[0]}`:x,o=document.createElement("option");o.value=v;o.textContent=t;o.selected=v===sel;el.append(o)})}
function toast(t){const e=$("toast");e.textContent=t;e.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add("hidden"),2200)}
function icon(c){return CATS.find(x=>x[0]===c)?.[1]||"🧾"}
function spent(){return state.expenses.reduce((s,e)=>s+num(e.homeAmount),0)}
function totalTripDays(){return state.trip?Math.max(1,days(state.trip.startDate,state.trip.endDate)):1}
function left(){if(!state.trip)return 0;const t=today();if(t>state.trip.endDate)return 0;return days(t<state.trip.startDate?state.trip.startDate:t,state.trip.endDate)}
function elapsed(){if(!state.trip)return 1;const t=today();if(t<state.trip.startDate)return 0;if(t>state.trip.endDate)return totalTripDays();return days(state.trip.startDate,t)}
function todaySpent(){const t=today();return state.expenses.filter(e=>e.date===t).reduce((s,e)=>s+num(e.homeAmount),0)}
function toHome(a,c,r){if(!state.trip)return 0;a=num(a);r=num(r,1);return c===state.trip.homeCurrency?a:r>0?a/r:0}
function rateKey(c){return state.trip?`${state.trip.homeCurrency}->${c}`:""}
function savedRate(c){return num(state.rates?.[rateKey(c)],0)}
function projected(){if(!state.trip)return 0;const e=elapsed(),s=spent();if(e<=0)return 0;return s/e*totalTripDays()}
function aggregate(field){const m=new Map;state.expenses.forEach(e=>{const k=e[field]||"Other";m.set(k,(m.get(k)||0)+num(e.homeAmount))});return[...m].map(([label,amount])=>({label,amount})).sort((a,b)=>b.amount-a.amount)}
function dailyRows(){const m=new Map;state.expenses.forEach(e=>m.set(e.date,(m.get(e.date)||0)+num(e.homeAmount)));return[...m].map(([date,amount])=>({date,amount})).sort((a,b)=>a.date.localeCompare(b.date))}
function health(){const t=state.trip,s=spent(),p=projected();if(!t)return{cls:"on-track",icon:"✓",title:"Ready",text:"Create your trip to start tracking."};if(s>t.budget)return{cls:"over",icon:"!",title:"Over budget",text:`You are ${money(s-t.budget,t.homeCurrency)} over your trip budget.`};if(elapsed()>0&&p>t.budget*1.05)return{cls:"watch",icon:"↗",title:"Watch your pace",text:`At this pace you may finish around ${money(p-t.budget,t.homeCurrency)} over budget.`};if(elapsed()>0&&p>0)return{cls:"on-track",icon:"✓",title:"On track",text:`At your current pace you may finish around ${money(Math.max(0,t.budget-p),t.homeCurrency)} under budget.`};return{cls:"on-track",icon:"✓",title:"Budget ready",text:`You have ${money(t.budget,t.homeCurrency)} planned for this trip.`}}
function renderHealth(){const h=health(),b=$("healthBanner");b.className=`health-banner ${h.cls}`;$("healthIcon").textContent=h.icon;$("healthTitle").textContent=h.title;$("healthText").textContent=h.text}
function smartInsights(){const t=state.trip,s=spent(),rows=aggregate("category"),drows=dailyRows(),out=[];if(!t)return out;const rem=t.budget-s,ld=left(),p=projected();if(elapsed()>0&&p>0){out.push({i:"🔮",t:"End-of-trip forecast",d:p>t.budget?`Current pace projects ${money(p,t.homeCurrency)}, above your budget.`:`Current pace projects ${money(p,t.homeCurrency)}, within your budget.`})}else out.push({i:"🧭",t:"Before your trip",d:`Your starting daily allowance is about ${money(t.budget/totalTripDays(),t.homeCurrency)}.`});if(rows.length){const top=rows[0],pct=s>0?Math.round(top.amount/s*100):0;out.push({i:icon(top.label),t:`${top.label} is your top category`,d:`It accounts for ${pct}% of your spending (${money(top.amount,t.homeCurrency)}).`})}if(drows.length){const biggest=drows.slice().sort((a,b)=>b.amount-a.amount)[0];out.push({i:"📈",t:"Highest-spend day",d:`${fmtDateLong(biggest.date)} was your biggest day at ${money(biggest.amount,t.homeCurrency)}.`})}if(ld>0){out.push({i:"☀️",t:"Daily spending room",d:`You can spend about ${money(Math.max(0,rem)/ld,t.homeCurrency)} per remaining day and stay within budget.`})}return out.slice(0,4)}
function renderInsights(){const el=$("smartInsights");el.replaceChildren();smartInsights().forEach(x=>{const row=document.createElement("div");row.className="insight";const i=document.createElement("div");i.className="insight-icon";i.textContent=x.i;const c=document.createElement("div"),a=document.createElement("strong"),b=document.createElement("span");a.textContent=x.t;b.textContent=x.d;c.append(a,b);row.append(i,c);el.append(row)})}
function render(){const has=!!state.trip;$("setupView").classList.toggle("hidden",has);$("mainView").classList.toggle("hidden",!has);$("nav").classList.toggle("hidden",!has);$("settingsShortcut").classList.toggle("hidden",!has);if(!has){$("headerTitle").textContent="TripSpend";$("headerSub").textContent="Travel spending, made simple.";return}const t=state.trip,s=spent(),rem=t.budget-s,ld=left(),pct=t.budget?clamp(s/t.budget*100,0,100):0,pr=projected();$("headerTitle").textContent=t.name;$("headerSub").textContent=`${t.destination} • ${fmtDate(t.startDate)} – ${fmtDate(t.endDate)}`;$("remainingValue").textContent=money(rem,t.homeCurrency).replace(" "+t.homeCurrency,"");$("remainingCode").textContent=t.homeCurrency;$("usedPct").textContent=`${Math.round(pct)}% used`;$("progressBar").style.width=pct+"%";$("budgetValue").textContent=money(t.budget,t.homeCurrency);$("spentValue").textContent=money(s,t.homeCurrency);$("safeToday").textContent=money(ld?Math.max(0,rem)/ld:0,t.homeCurrency);$("spentToday").textContent=money(todaySpent(),t.homeCurrency);$("projectedTotal").textContent=money(pr,t.homeCurrency);$("daysLeft").textContent=ld;renderHealth();renderInsights();renderList($("recentList"),state.expenses.slice().sort(sortNew).slice(0,5),false);renderList($("allList"),filtered(),true);const cats=aggregate("category").map(x=>({category:x.label,amount:x.amount}));bars($("topCategories"),cats.slice(0,4),true);bars($("categoryAnalytics"),cats,true);bars($("paymentAnalytics"),aggregate("paymentMethod"),false);const e=Math.max(1,elapsed());$("avgDay").textContent=money(s/e,t.homeCurrency);$("avgTransaction").textContent=money(state.expenses.length?s/state.expenses.length:0,t.homeCurrency);$("largest").textContent=money(Math.max(0,...state.expenses.map(x=>num(x.homeAmount))),t.homeCurrency);const dr=dailyRows(),big=dr.length?dr.slice().sort((a,b)=>b.amount-a.amount)[0]:null;$("biggestDay").textContent=big?fmtDate(big.date):"—";daily();fillSettings();renderRates();const f=filtered();$("expenseSummary").textContent=`${f.length} expense${f.length===1?"":"s"} • ${money(f.reduce((a,b)=>a+num(b.homeAmount),0),t.homeCurrency)}`}
function sortNew(a,b){return a.date===b.date?num(b.createdAt)-num(a.createdAt):a.date<b.date?1:-1}
function filtered(){const q=$("searchExpense").value.trim().toLowerCase(),c=$("filterCategory").value,p=$("filterPayment").value;return state.expenses.filter(e=>(!c||e.category===c)&&(!p||e.paymentMethod===p)&&(!q||`${e.note||""} ${e.category} ${e.paymentMethod}`.toLowerCase().includes(q))).slice().sort(sortNew)}
function renderList(el,items,actions){el.replaceChildren();if(!items.length){const x=document.createElement("div");x.className="empty";x.textContent="No expenses yet. Tap “Add Expense” when you spend something.";el.append(x);return}items.forEach(e=>{const row=document.createElement("div");row.className="expense";const i=document.createElement("div");i.className="expense-icon";i.textContent=icon(e.category);const m=document.createElement("div");m.className="expense-main";const a=document.createElement("strong");a.textContent=e.note?.trim()||e.category;const b=document.createElement("span");b.textContent=`${e.category} • ${fmtDateLong(e.date)} • ${e.paymentMethod}`;m.append(a,b);const side=document.createElement("div");side.className="expense-side";const hv=document.createElement("strong");hv.textContent=money(e.homeAmount,state.trip.homeCurrency);const ov=document.createElement("span");ov.textContent=e.currency===state.trip.homeCurrency?e.currency:money(e.amount,e.currency);side.append(hv,ov);row.append(i,m,side);if(actions){const ac=document.createElement("div");ac.className="expense-actions";const rep=document.createElement("button");rep.className="mini";rep.textContent="Repeat";rep.onclick=()=>openModal("",e);const ed=document.createElement("button");ed.className="mini";ed.textContent="Edit";ed.onclick=()=>openModal(e.id);const del=document.createElement("button");del.className="mini delete";del.textContent="Delete";del.onclick=()=>removeExpense(e.id);ac.append(rep,ed,del);row.append(ac)}el.append(row)})}
function bars(el,rows,withIcons){el.replaceChildren();if(!rows.length){const x=document.createElement("div");x.className="empty";x.textContent="Insights will appear here.";el.append(x);return}const mx=Math.max(...rows.map(x=>x.amount),1);rows.forEach(r=>{const label=r.category||r.label,w=document.createElement("div");w.className="bar-row";const meta=document.createElement("div");meta.className="bar-meta";const l=document.createElement("span");l.textContent=(withIcons?icon(label)+" ":"")+label;const v=document.createElement("strong");v.textContent=money(r.amount,state.trip.homeCurrency);meta.append(l,v);const tr=document.createElement("div");tr.className="bar-track";const f=document.createElement("div");f.className="bar-fill";f.style.width=Math.max(2,r.amount/mx*100)+"%";tr.append(f);w.append(meta,tr);el.append(w)})}
function daily(){const el=$("dailyAnalytics");el.replaceChildren();const rows=dailyRows().slice(-12);if(!rows.length){const x=document.createElement("div");x.className="empty";x.textContent="Daily spending will appear here.";el.append(x);return}const mx=Math.max(...rows.map(x=>x.amount),1);rows.forEach(r=>{const w=document.createElement("div");w.className="daily",d=document.createElement("span"),tr=document.createElement("div"),f=document.createElement("div"),v=document.createElement("strong");d.textContent=fmtDate(r.date);tr.className="bar-track";f.className="bar-fill";f.style.width=Math.max(2,r.amount/mx*100)+"%";tr.append(f);v.textContent=money(r.amount,state.trip.homeCurrency);w.append(d,tr,v);el.append(w)})}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo({top:0,behavior:"smooth"});if(id==="expenses")render()}
function openModal(id="",template=null){if(!state.trip)return;const e=id?state.expenses.find(x=>x.id===id):template;$("editId").value=id||"";$("modalTitle").textContent=id?"Edit Expense":template?"Repeat Expense":"Add Expense";opts($("expenseCurrency"),CURS,e?.currency||state.trip.tripCurrency);opts($("expenseCategory"),CATS,e?.category||"Food");opts($("paymentMethod"),PAYS,e?.paymentMethod||state.trip.defaultPayment||"Credit Card");$("expenseAmount").value=e?.amount??"";$("exchangeRate").value=e?.rate??"";$("expenseDate").value=id?(e?.date||today()):today();$("expenseNote").value=e?.note||"";suggestedCategory="";$("categorySuggestion").classList.add("hidden");rateUI(true);preview();duplicateCheck();$("modal").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){$("modal").classList.add("hidden");document.body.style.overflow="";$("expenseForm").reset();$("editId").value=""}
function rateUI(autofill=false){const c=$("expenseCurrency").value,same=c===state.trip.homeCurrency;$("rateWrap").classList.toggle("hidden",same);$("exchangeRate").required=!same;$("rateHelp").textContent=`Enter how many ${c} equal 1 ${state.trip.homeCurrency}.`;const sr=savedRate(c),mem=$("rateMemory");if(!same&&sr>0){mem.textContent=`Remembered rate: 1 ${state.trip.homeCurrency} = ${sr} ${c}`;mem.classList.remove("hidden");if(autofill&&!$("exchangeRate").value)$("exchangeRate").value=sr}else mem.classList.add("hidden")}
function preview(){if(!state.trip)return;const c=$("expenseCurrency").value,r=c===state.trip.homeCurrency?1:num($("exchangeRate").value);$("conversion").textContent="≈ "+money(toHome($("expenseAmount").value,c,r),state.trip.homeCurrency)}
function suggestCategory(){const q=$("expenseNote").value.trim().toLowerCase();suggestedCategory="";if(q.length<2){$("categorySuggestion").classList.add("hidden");return}for(const [cat,words] of Object.entries(KEYWORDS)){if(words.some(w=>q.includes(w))){suggestedCategory=cat;break}}if(suggestedCategory&&suggestedCategory!==$("expenseCategory").value){$("suggestionText").textContent=`Looks like ${icon(suggestedCategory)} ${suggestedCategory}`;$("categorySuggestion").classList.remove("hidden")}else $("categorySuggestion").classList.add("hidden")}
function duplicateCheck(){if(!state.trip)return;const id=$("editId").value,a=num($("expenseAmount").value),date=$("expenseDate").value,note=$("expenseNote").value.trim().toLowerCase(),cat=$("expenseCategory").value;const dup=a>0&&state.expenses.some(e=>e.id!==id&&Math.abs(num(e.amount)-a)<.000001&&e.currency===$("expenseCurrency").value&&e.date===date&&e.category===cat&&(!note||!e.note||e.note.trim().toLowerCase()===note));$("duplicateWarning").classList.toggle("hidden",!dup)}
function removeExpense(id){const e=state.expenses.find(x=>x.id===id);if(e&&confirm(`Delete ${e.note||e.category}?`)){state.expenses=state.expenses.filter(x=>x.id!==id);save();render();toast("Expense deleted")}}
function fillSettings(){const t=state.trip;$("sTripName").value=t.name;opts($("sDestination"),DESTS,t.destination);$("sStartDate").value=t.startDate;$("sEndDate").value=t.endDate;$("sBudget").value=t.budget;opts($("sHomeCurrency"),CURS,t.homeCurrency);opts($("sTripCurrency"),CURS,t.tripCurrency);opts($("sDefaultPayment"),PAYS,t.defaultPayment||"Credit Card")}
function renderRates(){const el=$("savedRates");el.replaceChildren();const rows=Object.entries(state.rates||{});if(!rows.length){const x=document.createElement("span");x.className="mini-summary";x.textContent="No saved rates yet.";el.append(x);return}rows.forEach(([pair,rate])=>{const r=document.createElement("div");r.className="rate-chip";const a=document.createElement("span"),b=document.createElement("strong");a.textContent=pair;b.textContent=rate;r.append(a,b);el.append(r)})}
function validDates(a,b){return a&&b&&a<=b}
$("setupForm").onsubmit=e=>{e.preventDefault();const a=$("startDate").value,b=$("endDate").value;if(!validDates(a,b))return toast("End date must be after start date");state={trip:{name:$("tripName").value.trim(),destination:$("destination").value,startDate:a,endDate:b,budget:num($("budget").value),homeCurrency:$("homeCurrency").value,tripCurrency:$("tripCurrency").value,defaultPayment:"Credit Card",createdAt:Date.now()},expenses:[],rates:{}};save();render();page("dashboard");toast("Trip created")};
$("settingsForm").onsubmit=e=>{e.preventDefault();const a=$("sStartDate").value,b=$("sEndDate").value;if(!validDates(a,b))return toast("End date must be after start date");const nh=$("sHomeCurrency").value;if(state.expenses.length&&nh!==state.trip.homeCurrency&&!confirm("Existing expenses will not be recalculated into the new home currency. Continue?"))return;state.trip={...state.trip,name:$("sTripName").value.trim(),destination:$("sDestination").value,startDate:a,endDate:b,budget:num($("sBudget").value),homeCurrency:nh,tripCurrency:$("sTripCurrency").value,defaultPayment:$("sDefaultPayment").value};save();render();toast("Trip updated")};
$("expenseForm").onsubmit=e=>{e.preventDefault();const a=num($("expenseAmount").value),c=$("expenseCurrency").value,r=c===state.trip.homeCurrency?1:num($("exchangeRate").value);if(a<=0)return toast("Enter an amount greater than zero");if(c!==state.trip.homeCurrency&&r<=0)return toast("Enter a valid exchange rate");const x={id:$("editId").value||`${Date.now()}-${Math.random().toString(16).slice(2)}`,amount:a,currency:c,rate:r,homeAmount:toHome(a,c,r),category:$("expenseCategory").value,paymentMethod:$("paymentMethod").value,date:$("expenseDate").value,note:$("expenseNote").value.trim(),createdAt:Date.now()},i=state.expenses.findIndex(y=>y.id===x.id);if(i>=0){x.createdAt=state.expenses[i].createdAt;state.expenses[i]=x}else state.expenses.push(x);if(c!==state.trip.homeCurrency)state.rates[rateKey(c)]=r;save();closeModal();render();toast(i>=0?"Expense updated":"Expense saved")};
function download(name,text,type){const blob=new Blob([text],{type}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(u)}
function exportBackup(){const name=(state.trip?.name||"tripspend").replace(/[^a-z0-9]+/gi,"-");download(`${name}-backup.json`,JSON.stringify({app:"TripSpend",version:2,exportedAt:new Date().toISOString(),data:state},null,2),"application/json");toast("Backup exported")}
function csvCell(v){const s=String(v??"");return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function exportCSV(){if(!state.trip)return;const h=["Date","Category","Note","Payment Method","Original Amount","Original Currency","Exchange Rate","Home Amount","Home Currency"],rows=state.expenses.slice().sort(sortNew).map(e=>[e.date,e.category,e.note,e.paymentMethod,e.amount,e.currency,e.rate,e.homeAmount,state.trip.homeCurrency]);download(`${state.trip.name.replace(/[^a-z0-9]+/gi,"-")}-expenses.csv`,[h,...rows].map(r=>r.map(csvCell).join(",")).join("\n"),"text/csv;charset=utf-8");toast("CSV exported")}
async function importBackup(file){if(!file)return;try{const x=JSON.parse(await file.text()),d=x.data||x;if(!d?.trip||!Array.isArray(d.expenses))throw Error();if(!confirm("Import this backup? It will replace the current trip in this browser."))return;state={trip:d.trip,expenses:d.expenses,rates:d.rates||{}};save();render();page("dashboard");toast("Backup imported")}catch{alert("That file is not a valid TripSpend backup.")}finally{$("importFile").value=""}}
$("exportBtn").onclick=exportBackup;$("csvBtn").onclick=exportCSV;$("importFile").onchange=e=>importBackup(e.target.files?.[0]);$("clearRates").onclick=()=>{if(confirm("Clear all remembered exchange rates?")){state.rates={};save();renderRates();toast("Saved rates cleared")}};$("deleteTrip").onclick=()=>{if(state.trip&&confirm(`Delete “${state.trip.name}” and all expenses?`)){state=blank();localStorage.removeItem(KEY);render();$("setupForm").reset();initDates();opts($("destination"),DESTS,"Thailand");opts($("homeCurrency"),CURS,"OMR");opts($("tripCurrency"),CURS,"THB");toast("Trip deleted")}};
["quickAdd","pageAdd","navAdd"].forEach(id=>$(id).onclick=()=>openModal());$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};$("expenseAmount").oninput=()=>{preview();duplicateCheck()};$("exchangeRate").oninput=preview;$("expenseCurrency").onchange=()=>{rateUI(true);preview();duplicateCheck()};$("expenseDate").onchange=duplicateCheck;$("expenseCategory").onchange=()=>{suggestCategory();duplicateCheck()};$("expenseNote").oninput=()=>{suggestCategory();duplicateCheck()};$("applySuggestion").onclick=()=>{if(suggestedCategory){$("expenseCategory").value=suggestedCategory;$("categorySuggestion").classList.add("hidden");duplicateCheck()}};$("searchExpense").oninput=render;$("filterCategory").onchange=render;$("filterPayment").onchange=render;$("seeAll").onclick=()=>page("expenses");$("settingsShortcut").onclick=()=>page("settings");document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>page(b.dataset.page));document.onkeydown=e=>{if(e.key==="Escape"&&!$("modal").classList.contains("hidden"))closeModal()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("installBtn").disabled=false});$("installBtn").onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else{const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$("installHelp").textContent=ios?"On iPhone: open TripSpend in Safari → Share → Add to Home Screen.":"Use your browser menu and choose Install app or Add to Home screen.";$("installHelp").classList.remove("hidden")}};
function initDates(){const t=today();$("startDate").value=t;const d=new Date;d.setDate(d.getDate()+6);$("endDate").value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
opts($("destination"),DESTS,"Thailand");opts($("sDestination"),DESTS,"Thailand");opts($("homeCurrency"),CURS,"OMR");opts($("tripCurrency"),CURS,"THB");opts($("sHomeCurrency"),CURS,"OMR");opts($("sTripCurrency"),CURS,"THB");opts($("sDefaultPayment"),PAYS,"Credit Card");opts($("expenseCurrency"),CURS,"THB");opts($("expenseCategory"),CATS,"Food");opts($("paymentMethod"),PAYS,"Credit Card");CATS.forEach(([n,i])=>{const o=document.createElement("option");o.value=n;o.textContent=`${i} ${n}`;$("filterCategory").append(o)});PAYS.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;$("filterPayment").append(o)});initDates();render();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();