(()=>{"use strict";
const KEY="tripspend.v1";
const CURS=["OMR","AED","SAR","QAR","KWD","BHD","USD","EUR","GBP","THB","IDR","JPY","MYR","SGD","INR","TRY","CHF","AUD","CAD","NZD","CNY","KRW","PHP","VND"];
const CATS=[["Food","🍽️"],["Transport","🚕"],["Hotel","🏨"],["Shopping","🛍️"],["Activities","🎟️"],["Flights","✈️"],["Coffee","☕"],["Groceries","🛒"],["Other","🧾"]];
const PAYS=["Cash","Credit Card","Debit Card","Apple Pay","Other"];
const $=id=>document.getElementById(id);
let state=load();
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==="object"?{trip:x.trip||null,expenses:Array.isArray(x.expenses)?x.expenses:[]}:{trip:null,expenses:[]}}catch{return{trip:null,expenses:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function today(){const d=new Date;return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function date(iso){if(!iso)return null;const [y,m,d]=iso.split("-").map(Number);return new Date(y,m-1,d)}
function days(a,b){const x=date(a),y=date(b);return x&&y?Math.max(0,Math.floor((y-x)/86400000)+1):0}
function money(v,c){const dp=["OMR","KWD","BHD"].includes(c)?3:2;return new Intl.NumberFormat(undefined,{minimumFractionDigits:dp,maximumFractionDigits:dp}).format(num(v))+" "+c}
function fmtDate(x){const d=date(x);return d?new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short"}).format(d):""}
function fmtDateLong(x){const d=date(x);return d?new Intl.DateTimeFormat(undefined,{weekday:"short",day:"numeric",month:"short"}).format(d):""}
function opts(sel,arr,val){sel.replaceChildren();arr.forEach(x=>{const o=document.createElement("option"),v=Array.isArray(x)?x[0]:x;o.value=v;o.textContent=Array.isArray(x)?`${x[1]} ${x[0]}`:x;o.selected=v===val;sel.append(o)})}
function toast(m){const t=$("toast");t.textContent=m;t.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add("hidden"),2000)}
function icon(c){return CATS.find(x=>x[0]===c)?.[1]||"🧾"}
function spent(){return state.expenses.reduce((s,e)=>s+num(e.homeAmount),0)}
function leftDays(){if(!state.trip)return 0;const t=today();if(t>state.trip.endDate)return 0;return days(t<state.trip.startDate?state.trip.startDate:t,state.trip.endDate)}
function elapsed(){if(!state.trip)return 1;const t=today(),end=t>state.trip.endDate?state.trip.endDate:t;return Math.max(1,days(state.trip.startDate,end))}
function toHome(a,c,r){if(!state.trip)return 0;if(c===state.trip.homeCurrency)return num(a);return num(r)>0?num(a)/num(r):0}
function sortNew(a,b){return a.date===b.date?num(b.createdAt)-num(a.createdAt):(a.date<b.date?1:-1)}
function render(){const yes=!!state.trip;$("setupView").classList.toggle("hidden",yes);$("mainView").classList.toggle("hidden",!yes);$("nav").classList.toggle("hidden",!yes);$("settingsShortcut").classList.toggle("hidden",!yes);if(!yes){$("headerTitle").textContent="TripSpend";$("headerSub").textContent="Travel spending, made simple.";return}const t=state.trip,s=spent(),rem=t.budget-s,p=t.budget>0?Math.min(100,Math.max(0,s/t.budget*100)):0,d=leftDays(),safe=d>0?Math.max(0,rem)/d:0;$("headerTitle").textContent=t.name;$("headerSub").textContent=`${t.destination} • ${fmtDate(t.startDate)} – ${fmtDate(t.endDate)}`;$("remainingValue").textContent=money(rem,t.homeCurrency).replace(" "+t.homeCurrency,"");$("remainingCode").textContent=t.homeCurrency;$("usedPct").textContent=`${Math.round(p)}% used`;$("progressBar").style.width=p+"%";$("budgetValue").textContent=money(t.budget,t.homeCurrency);$("spentValue").textContent=money(s,t.homeCurrency);$("safeToday").textContent=money(safe,t.homeCurrency);$("daysLeft").textContent=d;list($("recentList"),state.expenses.slice().sort(sortNew).slice(0,5),false);list($("allList"),filtered(),true);const agg=categories();bars($("topCategories"),agg.slice(0,4));bars($("categoryAnalytics"),agg);$("avgDay").textContent=money(s/elapsed(),t.homeCurrency);$("largest").textContent=money(state.expenses.reduce((m,e)=>Math.max(m,num(e.homeAmount)),0),t.homeCurrency);daily();fillSettings()}
function filtered(){const q=$("searchExpense").value.trim().toLowerCase(),c=$("filterCategory").value;return state.expenses.filter(e=>(!c||e.category===c)&&(!q||`${e.category} ${e.note||""} ${e.paymentMethod}`.toLowerCase().includes(q))).slice().sort(sortNew)}
function list(el,items,actions){el.replaceChildren();if(!items.length){const x=document.createElement("div");x.className="empty";x.textContent="No expenses yet. Tap “Add Expense” when you spend something.";el.append(x);return}items.forEach(e=>{const row=document.createElement("div");row.className="expense";const i=document.createElement("div");i.className="expense-icon";i.textContent=icon(e.category);const m=document.createElement("div");m.className="expense-main";const a=document.createElement("strong");a.textContent=e.note?.trim()||e.category;const b=document.createElement("span");b.textContent=`${e.category} • ${fmtDateLong(e.date)} • ${e.paymentMethod}`;m.append(a,b);const side=document.createElement("div");side.className="expense-side";const hv=document.createElement("strong");hv.textContent=money(e.homeAmount,state.trip.homeCurrency);const ov=document.createElement("span");ov.textContent=e.currency===state.trip.homeCurrency?e.currency:money(e.amount,e.currency);side.append(hv,ov);row.append(i,m,side);if(actions){const ac=document.createElement("div");ac.className="expense-actions";const ed=document.createElement("button");ed.className="mini";ed.textContent="Edit";ed.onclick=()=>openModal(e.id);const del=document.createElement("button");del.className="mini delete";del.textContent="Delete";del.onclick=()=>removeExpense(e.id);ac.append(ed,del);row.append(ac)}el.append(row)})}
function categories(){const m=new Map;state.expenses.forEach(e=>m.set(e.category,(m.get(e.category)||0)+num(e.homeAmount)));return[...m].map(([category,amount])=>({category,amount})).sort((a,b)=>b.amount-a.amount)}
function bars(el,rows){el.replaceChildren();if(!rows.length){const x=document.createElement("div");x.className="empty";x.textContent="Insights will appear here.";el.append(x);return}const mx=Math.max(...rows.map(x=>x.amount),1);rows.forEach(r=>{const w=document.createElement("div");w.className="bar-row";const meta=document.createElement("div");meta.className="bar-meta";const l=document.createElement("span");l.textContent=`${icon(r.category)} ${r.category}`;const v=document.createElement("strong");v.textContent=money(r.amount,state.trip.homeCurrency);meta.append(l,v);const tr=document.createElement("div");tr.className="bar-track";const f=document.createElement("div");f.className="bar-fill";f.style.width=Math.max(2,r.amount/mx*100)+"%";tr.append(f);w.append(meta,tr);el.append(w)})}
function daily(){const el=$("dailyAnalytics");el.replaceChildren();if(!state.expenses.length){const x=document.createElement("div");x.className="empty";x.textContent="Daily spending will appear here.";el.append(x);return}const m=new Map;state.expenses.forEach(e=>m.set(e.date,(m.get(e.date)||0)+num(e.homeAmount)));const rows=[...m].map(([date,amount])=>({date,amount})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-10),mx=Math.max(...rows.map(x=>x.amount),1);rows.forEach(r=>{const w=document.createElement("div");w.className="daily";const d=document.createElement("span");d.textContent=fmtDate(r.date);const tr=document.createElement("div");tr.className="bar-track";const f=document.createElement("div");f.className="bar-fill";f.style.width=Math.max(2,r.amount/mx*100)+"%";tr.append(f);const v=document.createElement("strong");v.textContent=money(r.amount,state.trip.homeCurrency);w.append(d,tr,v);el.append(w)})}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===id));scrollTo({top:0,behavior:"smooth"});if(id==="expenses")render()}
function openModal(id=""){if(!state.trip)return;const e=id?state.expenses.find(x=>x.id===id):null;$("editId").value=e?.id||"";$("modalTitle").textContent=e?"Edit Expense":"Add Expense";opts($("expenseCurrency"),CURS,e?.currency||state.trip.tripCurrency);opts($("expenseCategory"),CATS,e?.category||"Food");opts($("paymentMethod"),PAYS,e?.paymentMethod||"Credit Card");$("expenseAmount").value=e?.amount??"";$("exchangeRate").value=e?.rate??"";$("expenseDate").value=e?.date||today();$("expenseNote").value=e?.note||"";rateUI();preview();$("modal").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){$("modal").classList.add("hidden");document.body.style.overflow="";$("expenseForm").reset();$("editId").value=""}
function rateUI(){const c=$("expenseCurrency").value,same=c===state.trip.homeCurrency;$("rateWrap").classList.toggle("hidden",same);$("exchangeRate").required=!same;$("rateHelp").textContent=`Enter how many ${c} equal 1 ${state.trip.homeCurrency}.`}
function preview(){if(!state.trip)return;const c=$("expenseCurrency").value,r=c===state.trip.homeCurrency?1:num($("exchangeRate").value);$("conversion").textContent="≈ "+money(toHome($("expenseAmount").value,c,r),state.trip.homeCurrency)}
function removeExpense(id){const e=state.expenses.find(x=>x.id===id);if(e&&confirm(`Delete ${e.note||e.category}?`)){state.expenses=state.expenses.filter(x=>x.id!==id);save();render();toast("Expense deleted")}}
function fillSettings(){const t=state.trip;$("sTripName").value=t.name;$("sDestination").value=t.destination;$("sStartDate").value=t.startDate;$("sEndDate").value=t.endDate;$("sBudget").value=t.budget;opts($("sHomeCurrency"),CURS,t.homeCurrency);opts($("sTripCurrency"),CURS,t.tripCurrency)}
function validDates(a,b){return a&&b&&a<=b}
$("setupForm").onsubmit=e=>{e.preventDefault();const a=$("startDate").value,b=$("endDate").value;if(!validDates(a,b))return toast("End date must be after start date");state={trip:{name:$("tripName").value.trim(),destination:$("destination").value.trim(),startDate:a,endDate:b,budget:num($("budget").value),homeCurrency:$("homeCurrency").value,tripCurrency:$("tripCurrency").value,createdAt:Date.now()},expenses:[]};save();render();page("dashboard");toast("Trip created")};
$("settingsForm").onsubmit=e=>{e.preventDefault();const a=$("sStartDate").value,b=$("sEndDate").value;if(!validDates(a,b))return toast("End date must be after start date");const newHome=$("sHomeCurrency").value;if(state.expenses.length&&newHome!==state.trip.homeCurrency&&!confirm("Existing expenses will not be recalculated into the new home currency. Continue?"))return;state.trip={...state.trip,name:$("sTripName").value.trim(),destination:$("sDestination").value.trim(),startDate:a,endDate:b,budget:num($("sBudget").value),homeCurrency:newHome,tripCurrency:$("sTripCurrency").value};save();render();toast("Trip updated")};
$("expenseForm").onsubmit=e=>{e.preventDefault();const a=num($("expenseAmount").value),c=$("expenseCurrency").value,r=c===state.trip.homeCurrency?1:num($("exchangeRate").value);if(a<=0)return toast("Enter an amount greater than zero");if(c!==state.trip.homeCurrency&&r<=0)return toast("Enter a valid exchange rate");const x={id:$("editId").value||`${Date.now()}-${Math.random().toString(16).slice(2)}`,amount:a,currency:c,rate:r,homeAmount:toHome(a,c,r),category:$("expenseCategory").value,paymentMethod:$("paymentMethod").value,date:$("expenseDate").value,note:$("expenseNote").value.trim(),createdAt:Date.now()},i=state.expenses.findIndex(y=>y.id===x.id);if(i>=0){x.createdAt=state.expenses[i].createdAt;state.expenses[i]=x}else state.expenses.push(x);save();closeModal();render();toast(i>=0?"Expense updated":"Expense saved")};
function exportBackup(){const blob=new Blob([JSON.stringify({app:"TripSpend",version:1,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a"),name=(state.trip?.name||"tripspend").replace(/[^a-z0-9]+/gi,"-");a.href=u;a.download=`${name}-backup.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(u);toast("Backup exported")}
async function importBackup(file){if(!file)return;try{const x=JSON.parse(await file.text()),d=x.data||x;if(!d?.trip||!Array.isArray(d.expenses))throw Error();if(!confirm("Import this backup? It will replace the current trip in this browser."))return;state={trip:d.trip,expenses:d.expenses};save();render();page("dashboard");toast("Backup imported")}catch{alert("That file is not a valid TripSpend backup.")}finally{$("importFile").value=""}}
$("exportBtn").onclick=exportBackup;$("importFile").onchange=e=>importBackup(e.target.files?.[0]);$("deleteTrip").onclick=()=>{if(state.trip&&confirm(`Delete “${state.trip.name}” and all expenses?`)){state={trip:null,expenses:[]};localStorage.removeItem(KEY);render();$("setupForm").reset();initDates();opts($("homeCurrency"),CURS,"OMR");opts($("tripCurrency"),CURS,"THB");toast("Trip deleted")}};
["quickAdd","pageAdd","navAdd"].forEach(id=>$(id).onclick=()=>openModal());$("closeModal").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};$("expenseAmount").oninput=preview;$("exchangeRate").oninput=preview;$("expenseCurrency").onchange=()=>{rateUI();preview()};$("searchExpense").oninput=render;$("filterCategory").onchange=render;$("seeAll").onclick=()=>page("expenses");$("settingsShortcut").onclick=()=>page("settings");document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>page(b.dataset.page));document.onkeydown=e=>{if(e.key==="Escape"&&!$("modal").classList.contains("hidden"))closeModal()};
function initDates(){const t=today();$("startDate").value=t;const d=new Date;d.setDate(d.getDate()+6);$("endDate").value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
opts($("homeCurrency"),CURS,"OMR");opts($("tripCurrency"),CURS,"THB");opts($("sHomeCurrency"),CURS,"OMR");opts($("sTripCurrency"),CURS,"THB");opts($("expenseCurrency"),CURS,"THB");opts($("expenseCategory"),CATS,"Food");opts($("paymentMethod"),PAYS,"Credit Card");CATS.forEach(([n,i])=>{const o=document.createElement("option");o.value=n;o.textContent=`${i} ${n}`;$("filterCategory").append(o)});initDates();render();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();
