(() => {
  "use strict";
  const KEY="tripspend.language";
  const AR=new Map(Object.entries({"Home":"الرئيسية","Expenses":"المصروفات","Plan":"الخطة","Analytics":"التحليلات","Settings":"الإعدادات","Your trip at a glance":"رحلتك بنظرة سريعة","Current trip":"الرحلة الحالية","Country budgets":"ميزانيات الدول","WHERE YOU ARE":"موقعك الآن","YOUR ROUTE":"مسار رحلتك","TODAY":"اليوم","Manage Trips":"إدارة الرحلات","Manage Countries & Plans":"إدارة الدول والخطط","Manage Travelers":"إدارة المسافرين","Add another country":"إضافة دولة أخرى","Preferences & safety":"التفضيلات والأمان","Tools & data":"الأدوات والبيانات","Trip settings":"إعدادات الرحلة","Ask TripSpend AI":"اسأل TripSpend AI","Ask or make a change…":"اسأل أو اطلب تغييرًا…","Send question":"إرسال السؤال","Close TripSpend AI":"إغلاق TripSpend AI","Cancel":"إلغاء","Confirm":"تأكيد","Save":"حفظ","Delete":"حذف","Edit":"تعديل","Add expense":"إضافة مصروف","Add traveler":"إضافة مسافر","Trip budget":"ميزانية الرحلة","Budget":"الميزانية","Spent":"المصروف","Remaining":"المتبقي","Upcoming":"القادم","Today":"اليوم","This trip":"هذه الرحلة","Free beta":"نسخة تجريبية مجانية","CHECKING":"جارٍ التحقق","ONLINE":"متصل","OFFLINE":"غير متصل","Everyone is settled ✓":"تمت تسوية الجميع ✓","No travelers yet.":"لا يوجد مسافرون بعد.","View all travelers":"عرض كل المسافرين"}));
  let lang=localStorage.getItem(KEY)==="ar"?"ar":"en"; const originals=new WeakMap(); let busy=false;
  function textNode(n){if(n.nodeType!==3||!n.nodeValue.trim())return;if(!originals.has(n))originals.set(n,n.nodeValue);const o=originals.get(n),k=o.trim();n.nodeValue=lang==="ar"&&AR.has(k)?o.replace(k,AR.get(k)):o;}
  function walk(el){if(!(el instanceof Element))return;["placeholder","aria-label","title"].forEach(a=>{if(!el.hasAttribute(a))return;const d=`data-i18n-${a.replace("aria-label","aria")}`;if(!el.hasAttribute(d))el.setAttribute(d,el.getAttribute(a));const o=el.getAttribute(d);el.setAttribute(a,lang==="ar"&&AR.has(o)?AR.get(o):o);});el.childNodes.forEach(n=>n.nodeType===3?textNode(n):n.nodeType===1&&walk(n));}
  function apply(){if(busy)return;busy=true;document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.body?.classList.toggle("lang-ar",lang==="ar");if(document.body)walk(document.body);const b=document.getElementById("languageToggle");if(b){b.textContent=lang==="ar"?"EN":"عربي";b.setAttribute("aria-label",lang==="ar"?"Switch to English":"التبديل إلى العربية");}window.dispatchEvent(new CustomEvent("tripspend:language",{detail:{language:lang}}));busy=false;}
  function install(){if(document.getElementById("languageToggle"))return;const h=document.querySelector(".dashboard-welcome");if(!h)return;const b=document.createElement("button");b.id="languageToggle";b.type="button";b.className="language-toggle";b.addEventListener("click",()=>{lang=lang==="ar"?"en":"ar";localStorage.setItem(KEY,lang);apply();});h.appendChild(b);}
  window.TripSpendI18n={language:()=>lang,setLanguage(v){lang=v==="ar"?"ar":"en";localStorage.setItem(KEY,lang);apply();}};
  addEventListener("DOMContentLoaded",()=>{install();apply();new MutationObserver(()=>{install();apply();}).observe(document.body,{childList:true,subtree:true,characterData:true});});
})();
